language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ravijoh/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true ravijoh/docker-react npm run test

